import type { QuestChainFixture } from './addonEvents';

export const CLASSIC_QUEST_CHAINS: QuestChainFixture[] = [
  {
    id: 'alliance-defias-brotherhood',
    title: 'The Defias Brotherhood',
    faction: 'Alliance',
    era: 'classic',
    recommendedHero: 'Human or Dwarf hero, level 14-22',
    zonePath: ['Westfall', 'Redridge Mountains', 'Stormwind City', 'Westfall', 'The Deadmines'],
    summary:
      'A Westfall investigation that follows the Defias threat from local militia reports through SI:7 intelligence and into the Deadmines.',
    versionNotes:
      'Classic/pre-Cataclysm chain. Retail Westfall uses a different post-Cataclysm storyline and quest ID range.',
    steps: [
      {
        stepId: 'defias-65',
        questId: 65,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=65/the-defias-brotherhood',
        zone: 'Westfall',
        npcName: 'Gryan Stoutmantle',
        npcId: 234,
        storyCard: {
          moment: 'The People’s Militia sends the hero beyond Westfall for intelligence.',
          setup: 'Westfall is buckling under Defias violence, and Gryan Stoutmantle needs proof of who is coordinating it.',
          playerAction: 'The hero travels to Lakeshire to find Wiley, a rogue informant with a lead on the Defias.',
          outcome: 'The investigation expands beyond simple banditry into a larger conspiracy.',
          emotionalWeight: 'Uneasy discovery: Westfall’s suffering may be tied to Stormwind’s failures.',
          chronicleEntry: 'Began the Defias investigation for Gryan Stoutmantle and sought Wiley’s intelligence in Lakeshire.',
          tags: ['defias', 'westfall', 'redridge', 'investigation', 'militia'],
        },
        events: [
          { kind: 'quest_detail', wowEvent: 'QUEST_DETAIL', summary: 'Viewed Gryan Stoutmantle’s Defias investigation lead.', npcName: 'Gryan Stoutmantle' },
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the mission to find Wiley in Lakeshire.', npcName: 'Gryan Stoutmantle', playerLevel: 14 },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Traveled from Westfall to Lakeshire in Redridge.', zone: 'Redridge Mountains', subZone: 'Lakeshire' },
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Questioned Wiley at the Lakeshire inn.', zone: 'Redridge Mountains', npcName: 'Wiley' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Found Wiley and confirmed he has Defias intelligence.', zone: 'Redridge Mountains', npcName: 'Wiley' },
        ],
      },
      {
        stepId: 'defias-132',
        questId: 132,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=132/the-defias-brotherhood',
        zone: 'Redridge Mountains',
        npcName: 'Wiley',
        storyCard: {
          moment: 'Wiley’s note points back to Gryan with a sharper lead.',
          setup: 'The Defias are no random gang; the trail points toward organized craftsmen and old grievances.',
          playerAction: 'The hero carries Wiley’s message back across the road to Westfall.',
          outcome: 'Gryan has enough to send the matter toward Stormwind intelligence.',
          emotionalWeight: 'Suspicion hardens into proof that the conspiracy has roots.',
          chronicleEntry: 'Returned Wiley’s intelligence to Gryan, revealing the Defias threat was organized far beyond Westfall’s roads.',
          tags: ['defias', 'westfall', 'wiley', 'message', 'stonemasons'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Wiley’s request to deliver his note.', npcName: 'Wiley' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Returned from Redridge to Westfall.', zone: 'Westfall' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Delivered Wiley’s intelligence to Gryan.', zone: 'Westfall', npcName: 'Gryan Stoutmantle' },
        ],
      },
      {
        stepId: 'defias-135',
        questId: 135,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=135/the-defias-brotherhood',
        zone: 'Westfall',
        npcName: 'Gryan Stoutmantle',
        storyCard: {
          moment: 'The militia asks SI:7 to identify the hand behind the Defias.',
          setup: 'Gryan needs Stormwind’s spymaster to connect Wiley’s evidence to a name.',
          playerAction: 'The hero travels to Stormwind and brings the evidence to Mathias Shaw.',
          outcome: 'SI:7 confirms the investigation is serious enough for a formal dossier.',
          emotionalWeight: 'The local Westfall crisis reaches the capital’s intelligence network.',
          chronicleEntry: 'Carried the Defias evidence to Mathias Shaw of SI:7, pulling Stormwind into Westfall’s crisis.',
          tags: ['si7', 'stormwind', 'mathias-shaw', 'defias', 'intelligence'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the order to consult Mathias Shaw.', npcName: 'Gryan Stoutmantle' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Entered Stormwind City.', zone: 'Stormwind City' },
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Met Mathias Shaw at SI:7.', zone: 'Stormwind City', npcName: 'Mathias Shaw' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Delivered the Defias lead to Mathias Shaw.', zone: 'Stormwind City', npcName: 'Mathias Shaw' },
        ],
      },
      {
        stepId: 'defias-141',
        questId: 141,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=141/the-defias-brotherhood',
        zone: 'Stormwind City',
        npcName: 'Mathias Shaw',
        storyCard: {
          moment: 'SI:7 names Edwin VanCleef as the Defias leader.',
          setup: 'Shaw’s dossier ties the Defias to the betrayed Stonemasons and their former leader.',
          playerAction: 'The hero returns the dossier to Gryan in Westfall.',
          outcome: 'The militia finally has a target, not just a banner to chase.',
          emotionalWeight: 'Revelation with a bitter edge: the villain was forged by a kingdom’s unpaid debt.',
          chronicleEntry: 'Returned Shaw’s dossier to Westfall, revealing Edwin VanCleef as the mind behind the Defias Brotherhood.',
          tags: ['edwin-vancleef', 'stonemasons', 'stormwind', 'betrayal', 'westfall'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Shaw’s dossier for Gryan.', npcName: 'Mathias Shaw' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Returned to Westfall from Stormwind.', zone: 'Westfall' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Brought Shaw’s dossier back to Gryan.', zone: 'Westfall', npcName: 'Gryan Stoutmantle' },
        ],
      },
      {
        stepId: 'defias-142',
        questId: 142,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=142/the-defias-brotherhood',
        zone: 'Westfall',
        npcName: 'Gryan Stoutmantle',
        storyCard: {
          moment: 'The hero intercepts a moving Defias courier.',
          setup: 'Gryan needs the Brotherhood’s current orders, not only SI:7 history.',
          playerAction: 'The hero hunts the roads for a Defias Messenger and recovers his message.',
          outcome: 'The path to the Brotherhood’s hidden base begins to open.',
          emotionalWeight: 'Momentum: the investigation turns from research to pursuit.',
          chronicleEntry: 'Intercepted a Defias Messenger on Westfall’s roads and recovered orders that pointed toward the Brotherhood’s hidden base.',
          tags: ['defias-messenger', 'westfall', 'ambush', 'orders'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the hunt for a Defias Messenger.', npcName: 'Gryan Stoutmantle' },
          { kind: 'unit_kill', wowEvent: 'COMBAT_LOG_EVENT_UNFILTERED', summary: 'Defeated the roving Defias Messenger.', unitName: 'Defias Messenger' },
          { kind: 'quest_objective_progress', wowEvent: 'QUEST_PROGRESS', summary: 'Recovered the courier’s message.', itemName: 'A Mysterious Message' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Delivered the Defias message to Gryan.', npcName: 'Gryan Stoutmantle' },
        ],
      },
      {
        stepId: 'defias-155',
        questId: 155,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=155/the-defias-brotherhood',
        zone: 'Westfall',
        npcName: 'Defias Traitor',
        npcId: 467,
        storyCard: {
          moment: 'A captured traitor reveals the hidden path to the Deadmines.',
          setup: 'The Brotherhood’s base is concealed, and only someone who knows the route can expose it.',
          playerAction: 'The hero escorts the Defias Traitor through hostile territory.',
          outcome: 'The Deadmines entrance is revealed and the final assault becomes possible.',
          emotionalWeight: 'Tense transition: trust a traitor long enough to end the conspiracy.',
          chronicleEntry: 'Escorted the Defias Traitor through Westfall and uncovered the hidden approach to the Deadmines.',
          tags: ['escort', 'defias-traitor', 'deadmines', 'westfall'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the escort with the Defias Traitor.', npcName: 'Defias Traitor' },
          { kind: 'escort_start', wowEvent: 'UNIT_QUEST_LOG_CHANGED', summary: 'Started escorting the Defias Traitor.', npcName: 'Defias Traitor' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED', summary: 'Reached the hidden Deadmines approach.', zone: 'Westfall', subZone: 'The Deadmines entrance' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Reported the revealed entrance back to Gryan.', npcName: 'Gryan Stoutmantle' },
        ],
      },
      {
        stepId: 'defias-166',
        questId: 166,
        questName: 'The Defias Brotherhood',
        wowheadUrl: 'https://classic.wowhead.com/quest=166/the-defias-brotherhood',
        zone: 'The Deadmines',
        npcName: 'Gryan Stoutmantle',
        npcId: 234,
        storyCard: {
          moment: 'The hidden war beneath Westfall ends aboard VanCleef’s ship.',
          setup: 'SI:7 has named VanCleef, the entrance has been found, and the militia needs proof the Defias leader is dead.',
          playerAction: 'The hero enters the Deadmines, fights through the Brotherhood, and defeats Edwin VanCleef.',
          outcome: 'The Defias lose their leader and Westfall gains proof that the threat can be broken.',
          emotionalWeight: 'A grim victory: justice for Westfall, but rooted in Stormwind’s older betrayal.',
          chronicleEntry: 'Defeated Edwin VanCleef in the Deadmines and returned proof to Gryan Stoutmantle, breaking the first great Defias conspiracy in Westfall.',
          tags: ['deadmines', 'edwin-vancleef', 'defias', 'justice', 'betrayal', 'grim-victory'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the final assault on Edwin VanCleef.', npcName: 'Gryan Stoutmantle', playerLevel: 20 },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Entered the Deadmines.', zone: 'The Deadmines' },
          { kind: 'unit_kill', wowEvent: 'COMBAT_LOG_EVENT_UNFILTERED', summary: 'Defeated Edwin VanCleef aboard his ship.', unitName: 'Edwin VanCleef' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned proof of VanCleef’s defeat to Gryan.', zone: 'Westfall', npcName: 'Gryan Stoutmantle', playerLevel: 22 },
        ],
      },
    ],
  },
  {
    id: 'alliance-crown-earth',
    title: 'Crown of the Earth',
    faction: 'Alliance',
    era: 'classic',
    recommendedHero: 'Night Elf hero, level 2-10',
    zonePath: ['Shadowglen', 'Dolanaar', 'Oracle Glade', 'Darnassus'],
    summary:
      'A Night Elf ritual chain that carries moonwell waters across Teldrassil and ends before Fandral Staghelm.',
    versionNotes:
      'Classic/pre-BfA fixture. Retail Night Elf starts changed after Teldrassil’s destruction.',
    steps: [
      {
        stepId: 'crown-920',
        questId: 920,
        questName: "Tenaron's Summons",
        wowheadUrl: 'https://classic.wowhead.com/quest=920/tenarons-summons',
        zone: 'Shadowglen',
        npcName: 'Tenaron Stormgrip',
        npcId: 3514,
        storyCard: {
          moment: 'A new Night Elf is called deeper into Aldrassil’s teaching.',
          setup: 'The hero is sent to Tenaron Stormgrip to begin learning Teldrassil’s sacred purpose.',
          playerAction: 'The hero climbs Aldrassil and speaks with Tenaron.',
          outcome: 'The ritual of the moonwells begins.',
          emotionalWeight: 'Quiet initiation into a wounded people’s hope.',
          chronicleEntry: 'Answered Tenaron Stormgrip’s summons in Shadowglen and began learning the sacred burden of Teldrassil.',
          tags: ['teldrassil', 'shadowglen', 'tenaron', 'night-elf', 'ritual'],
        },
        events: [
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Spoke with Tenaron Stormgrip in Aldrassil.', npcName: 'Tenaron Stormgrip', playerLevel: 2 },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Answered Tenaron’s summons.', npcName: 'Tenaron Stormgrip' },
        ],
      },
      {
        stepId: 'crown-921',
        questId: 921,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=921/crown-of-the-earth',
        zone: 'Shadowglen',
        npcName: 'Tenaron Stormgrip',
        storyCard: {
          moment: 'The hero carries the first phial to a moonwell.',
          setup: 'Teldrassil’s blessing is uncertain, and its waters must be tested through sacred wells.',
          playerAction: 'The hero fills a crystal phial at the moonwell north of Aldrassil.',
          outcome: 'The first vessel is charged for the larger ritual.',
          emotionalWeight: 'Reverence mixed with doubt over Teldrassil’s future.',
          chronicleEntry: 'Filled the first phial at Shadowglen’s moonwell, taking part in the ritual to understand Teldrassil’s blessing.',
          tags: ['moonwell', 'teldrassil', 'ritual', 'phial'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Tenaron’s moonwell ritual task.', npcName: 'Tenaron Stormgrip', playerLevel: 3 },
          { kind: 'item_use', wowEvent: 'QUEST_PROGRESS', summary: 'Filled the Crystal Phial at the moonwell.', itemName: 'Crystal Phial' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned the filled phial to Tenaron.', npcName: 'Tenaron Stormgrip' },
        ],
      },
      {
        stepId: 'crown-928',
        questId: 928,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=928/crown-of-the-earth',
        zone: 'Shadowglen',
        npcName: 'Tenaron Stormgrip',
        storyCard: {
          moment: 'The ritual moves from Shadowglen toward Dolanaar.',
          setup: 'Tenaron sends the partially filled vessel south to Corithras Moonrage.',
          playerAction: 'The hero travels the road from Shadowglen to Dolanaar.',
          outcome: 'A broader druidic ritual begins to unfold across Teldrassil.',
          emotionalWeight: 'A first step out of the sheltered boughs into a wider responsibility.',
          chronicleEntry: 'Carried the moonwell vessel from Shadowglen to Corithras Moonrage in Dolanaar.',
          tags: ['dolanaar', 'corithras', 'teldrassil', 'journey'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the delivery to Corithras Moonrage.', npcName: 'Tenaron Stormgrip' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED', summary: 'Traveled to Dolanaar.', zone: 'Teldrassil', subZone: 'Dolanaar', playerLevel: 5 },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Delivered the vessel to Corithras.', npcName: 'Corithras Moonrage' },
        ],
      },
      {
        stepId: 'crown-929',
        questId: 929,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=929/crown-of-the-earth',
        zone: 'Dolanaar',
        npcName: 'Corithras Moonrage',
        npcId: 3515,
        storyCard: {
          moment: 'The hero draws from the moonwell near Starbreeze Village.',
          setup: 'Corithras needs the next phial filled where Teldrassil’s corruption presses closer.',
          playerAction: 'The hero travels east and fills the Jade Phial.',
          outcome: 'Another sacred water joins the vessel.',
          emotionalWeight: 'Ritual duty performed under the shadow of local danger.',
          chronicleEntry: 'Filled the Jade Phial near Starbreeze Village, carrying the moonwell ritual farther into Teldrassil.',
          tags: ['starbreeze', 'jade-phial', 'moonwell', 'corithras'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Corithras’s next phial task.', npcName: 'Corithras Moonrage' },
          { kind: 'item_use', wowEvent: 'QUEST_PROGRESS', summary: 'Filled the Jade Phial at the eastern moonwell.', itemName: 'Jade Phial' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned the Jade Phial to Corithras.', npcName: 'Corithras Moonrage' },
        ],
      },
      {
        stepId: 'crown-933',
        questId: 933,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=933/crown-of-the-earth',
        zone: 'Teldrassil',
        npcName: 'Corithras Moonrage',
        storyCard: {
          moment: 'The ritual pushes toward the Pools of Arlithrien.',
          setup: 'The next well lies near Gnarlpine danger and deeper questions about the tree.',
          playerAction: 'The hero fills the Tourmaline Phial southeast of Darnassus.',
          outcome: 'The vessel nears completion.',
          emotionalWeight: 'A sacred errand becomes a tour through a fragile homeland.',
          chronicleEntry: 'Filled the Tourmaline Phial near the Pools of Arlithrien, continuing the moonwell rite across Teldrassil.',
          tags: ['tourmaline-phial', 'pools-of-arlithrien', 'gnarlpine', 'teldrassil'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the Tourmaline Phial task.', npcName: 'Corithras Moonrage', playerLevel: 7 },
          { kind: 'item_use', wowEvent: 'QUEST_PROGRESS', summary: 'Filled the Tourmaline Phial.', itemName: 'Tourmaline Phial' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned to Corithras with the filled phial.', npcName: 'Corithras Moonrage' },
        ],
      },
      {
        stepId: 'crown-934',
        questId: 934,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=934/crown-of-the-earth',
        zone: 'Oracle Glade',
        npcName: 'Corithras Moonrage',
        storyCard: {
          moment: 'The hero visits the Oracle Glade moonwell beneath the great tree.',
          setup: 'The final phial must be filled at one of Teldrassil’s strongest sacred places.',
          playerAction: 'The hero reaches the Oracle Glade and fills the Amethyst Phial.',
          outcome: 'The vessel is ready to be brought to Darnassus.',
          emotionalWeight: 'The rite reaches its most solemn point.',
          chronicleEntry: 'Filled the Amethyst Phial at Oracle Glade, completing the moonwell vessel for Darnassus.',
          tags: ['oracle-glade', 'amethyst-phial', 'moonwell', 'sacred-rite'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the final phial task.', npcName: 'Corithras Moonrage' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED', summary: 'Entered Oracle Glade.', zone: 'Teldrassil', subZone: 'Oracle Glade' },
          { kind: 'item_use', wowEvent: 'QUEST_PROGRESS', summary: 'Filled the Amethyst Phial.', itemName: 'Amethyst Phial' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned the completed phial to Corithras.', npcName: 'Corithras Moonrage' },
        ],
      },
      {
        stepId: 'crown-935',
        questId: 935,
        questName: 'Crown of the Earth',
        wowheadUrl: 'https://classic.wowhead.com/quest=935/crown-of-the-earth',
        zone: 'Darnassus',
        npcName: 'Fandral Staghelm',
        npcId: 3516,
        storyCard: {
          moment: 'The completed moonwell vessel is brought before Fandral Staghelm.',
          setup: 'The ritual culminates in Darnassus before the archdruid most tied to Teldrassil’s controversial creation.',
          playerAction: 'The hero delivers the vessel to Fandral.',
          outcome: 'The hero becomes part of Teldrassil’s larger spiritual question.',
          emotionalWeight: 'A quiet achievement shadowed by uncertainty about the world tree’s blessing.',
          chronicleEntry: 'Brought the completed moonwell vessel to Fandral Staghelm in Darnassus, carrying Teldrassil’s unanswered spiritual burden with it.',
          tags: ['darnassus', 'fandral-staghelm', 'teldrassil', 'world-tree', 'moonwell'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the delivery to Fandral Staghelm.', npcName: 'Corithras Moonrage', playerLevel: 9 },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Entered Darnassus.', zone: 'Darnassus' },
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Met Fandral Staghelm.', npcName: 'Fandral Staghelm' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Delivered the completed moonwell vessel to Fandral.', npcName: 'Fandral Staghelm', playerLevel: 10 },
        ],
      },
    ],
  },
  {
    id: 'horde-rites-earthmother',
    title: 'Rites of the Earthmother',
    faction: 'Horde',
    era: 'classic',
    recommendedHero: 'Tauren hero, level 5-10',
    zonePath: ['Bloodhoof Village', 'Mulgore', 'Red Rocks', 'Thunder Bluff'],
    summary:
      'A Tauren rite chain moving from village elder guidance through vision, ancestral wisdom, Cairne Bloodhoof, and a named kodo hunt.',
    versionNotes:
      'Classic/pre-Cataclysm Mulgore chain. Retail Tauren starting flow has different structure and quest IDs.',
    steps: [
      {
        stepId: 'rites-767',
        questId: 767,
        questName: 'Rite of Vision',
        wowheadUrl: 'https://classic.wowhead.com/quest=767/rite-of-vision',
        zone: 'Bloodhoof Village',
        npcName: 'Zarlman Two-Moons',
        npcId: 3054,
        storyCard: {
          moment: 'The hero begins the Rite of Vision in Bloodhoof Village.',
          setup: 'The tribe’s elder prepares the young Tauren for a spiritual trial.',
          playerAction: 'The hero seeks Zarlman Two-Moons and accepts the first rite.',
          outcome: 'The path toward vision and wisdom opens.',
          emotionalWeight: 'An initiation rooted in trust, ancestry, and the Earthmother.',
          chronicleEntry: 'Began the Rite of Vision with Zarlman Two-Moons in Bloodhoof Village.',
          tags: ['tauren', 'earthmother', 'rite-of-vision', 'bloodhoof-village'],
        },
        events: [
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Spoke with Zarlman Two-Moons about the Rite of Vision.', npcName: 'Zarlman Two-Moons', playerLevel: 5 },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Presented yourself to Zarlman for the rite.', npcName: 'Zarlman Two-Moons' },
        ],
      },
      {
        stepId: 'rites-771',
        questId: 771,
        questName: 'Rite of Vision',
        wowheadUrl: 'https://classic.wowhead.com/quest=771/rite-of-vision',
        zone: 'Mulgore',
        npcName: 'Zarlman Two-Moons',
        storyCard: {
          moment: 'The hero gathers the materials for the Water of the Seers.',
          setup: 'Zarlman needs sacred ingredients drawn from Mulgore’s wells and trees.',
          playerAction: 'The hero gathers Well Stones and Ambercorn.',
          outcome: 'The ritual drink can be prepared.',
          emotionalWeight: 'A practical task made sacred by purpose.',
          chronicleEntry: 'Gathered Well Stones and Ambercorn across Mulgore so Zarlman could prepare the Water of the Seers.',
          tags: ['mulgore', 'gathering', 'water-of-the-seers', 'ritual'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the gathering task for the Water of the Seers.', npcName: 'Zarlman Two-Moons', playerLevel: 6 },
          { kind: 'quest_objective_progress', wowEvent: 'QUEST_PROGRESS', summary: 'Gathered Well Stones from Mulgore’s wells.', itemName: 'Well Stone' },
          { kind: 'quest_objective_progress', wowEvent: 'QUEST_PROGRESS', summary: 'Gathered Ambercorn from Mulgore’s trees.', itemName: 'Ambercorn' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned the ritual components to Zarlman.', npcName: 'Zarlman Two-Moons' },
        ],
      },
      {
        stepId: 'rites-772',
        questId: 772,
        questName: 'Rite of Vision',
        wowheadUrl: 'https://classic.wowhead.com/quest=772/rite-of-vision',
        zone: 'Bloodhoof Village',
        npcName: 'Zarlman Two-Moons',
        storyCard: {
          moment: 'The hero drinks the Water of the Seers and follows a vision.',
          setup: 'The rite asks the hero to trust what the spirit world reveals.',
          playerAction: 'The hero drinks at the tribal fire and follows the vision’s guidance.',
          outcome: 'The hero is directed toward the next rite.',
          emotionalWeight: 'Mystical surrender: the plains become a map of spirit and duty.',
          chronicleEntry: 'Drank the Water of the Seers at Bloodhoof Village and followed the vision toward the next Tauren rite.',
          tags: ['vision', 'spirit', 'bloodhoof-village', 'water-of-the-seers'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the ritual vision step.', npcName: 'Zarlman Two-Moons' },
          { kind: 'item_use', wowEvent: 'QUEST_PROGRESS', summary: 'Drank the Water of the Seers beside the tribal fire.', itemName: 'Water of the Seers' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Completed the vision rite.', npcName: 'Zarlman Two-Moons', playerLevel: 7 },
        ],
      },
      {
        stepId: 'rites-773',
        questId: 773,
        questName: 'Rite of Wisdom',
        wowheadUrl: 'https://classic.wowhead.com/quest=773/rite-of-wisdom',
        zone: 'Red Rocks',
        npcName: 'Ancestral Spirit',
        npcId: 2994,
        storyCard: {
          moment: 'The hero seeks an ancestral blessing at Red Rocks.',
          setup: 'The vision points east of Thunder Bluff to an Ancestral Spirit.',
          playerAction: 'The hero travels to Red Rocks and receives the spirit’s guidance.',
          outcome: 'The rite of wisdom confirms the hero’s place in Tauren tradition.',
          emotionalWeight: 'Communion across generations.',
          chronicleEntry: 'Sought the Ancestral Spirit at Red Rocks and received guidance in the Rite of Wisdom.',
          tags: ['ancestral-spirit', 'red-rocks', 'wisdom', 'tauren'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the journey to Red Rocks.', npcName: 'Zarlman Two-Moons' },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED', summary: 'Reached Red Rocks in Mulgore.', zone: 'Mulgore', subZone: 'Red Rocks' },
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Communed with the Ancestral Spirit.', npcName: 'Ancestral Spirit' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Completed the Rite of Wisdom before the Ancestral Spirit.', npcName: 'Ancestral Spirit' },
        ],
      },
      {
        stepId: 'rites-775',
        questId: 775,
        questName: 'Journey into Thunder Bluff',
        wowheadUrl: 'https://classic.wowhead.com/quest=775/journey-into-thunder-bluff',
        zone: 'Thunder Bluff',
        npcName: 'Cairne Bloodhoof',
        npcId: 3057,
        storyCard: {
          moment: 'The hero ascends Thunder Bluff to meet Cairne Bloodhoof.',
          setup: 'The Ancestral Spirit sends the hero to the high mesa and the Horde’s Tauren chieftain.',
          playerAction: 'The hero enters Thunder Bluff and presents themselves to Cairne.',
          outcome: 'The rite becomes a public charge before the Tauren leader.',
          emotionalWeight: 'Awe and belonging under the eyes of a people’s chieftain.',
          chronicleEntry: 'Journeyed into Thunder Bluff and stood before Cairne Bloodhoof after receiving the ancestral blessing.',
          tags: ['thunder-bluff', 'cairne-bloodhoof', 'tauren', 'chieftain'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the call to Thunder Bluff.', npcName: 'Ancestral Spirit', playerLevel: 8 },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Entered Thunder Bluff.', zone: 'Thunder Bluff' },
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Spoke with Cairne Bloodhoof.', npcName: 'Cairne Bloodhoof' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Presented yourself to Cairne Bloodhoof.', npcName: 'Cairne Bloodhoof' },
        ],
      },
      {
        stepId: 'rites-776',
        questId: 776,
        questName: 'Rites of the Earthmother',
        wowheadUrl: 'https://classic.wowhead.com/quest=776/rites-of-the-earthmother',
        zone: 'Mulgore',
        npcName: 'Cairne Bloodhoof',
        npcId: 3057,
        storyCard: {
          moment: 'Cairne sends the hero to hunt Arra’chea, the mighty kodo.',
          setup: 'The final rite tests whether the hero can act with strength, patience, and respect for the plains.',
          playerAction: 'The hero tracks and slays Arra’chea, then returns the horn to Cairne.',
          outcome: 'The rites are completed before the High Chieftain.',
          emotionalWeight: 'A solemn hunt that proves worth without forgetting reverence.',
          chronicleEntry: 'Tracked and slew Arra’chea on the plains of Mulgore, completing the Rites of the Earthmother before Cairne Bloodhoof.',
          tags: ['arrachea', 'kodo', 'mulgore', 'cairne-bloodhoof', 'rite-complete'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Cairne’s final hunt.', npcName: 'Cairne Bloodhoof', playerLevel: 9 },
          { kind: 'zone_changed', wowEvent: 'ZONE_CHANGED_NEW_AREA', summary: 'Returned to the plains of Mulgore.', zone: 'Mulgore' },
          { kind: 'unit_kill', wowEvent: 'COMBAT_LOG_EVENT_UNFILTERED', summary: 'Slew Arra’chea, the named kodo.', unitName: "Arra'chea" },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned Arra’chea’s horn to Cairne.', npcName: 'Cairne Bloodhoof', playerLevel: 10 },
        ],
      },
    ],
  },
  {
    id: 'horde-valley-trials',
    title: 'Valley of Trials',
    faction: 'Horde',
    era: 'classic',
    recommendedHero: 'Orc or Troll hero, level 1-6',
    zonePath: ['Valley of Trials', 'Durotar'],
    summary:
      'A compact Horde starter chain that tests race-gated intro steps, kill objectives, a named scorpid, and early survival stakes.',
    versionNotes:
      'Classic fixture. Orcs start with quest 787; Trolls can start with quest 4641 before both paths converge at Gornek.',
    steps: [
      {
        stepId: 'valley-787',
        questId: 787,
        questName: 'The New Horde',
        wowheadUrl: 'https://classic.wowhead.com/quest=787/the-new-horde',
        zone: 'Valley of Trials',
        npcName: 'Eitrigg',
        storyCard: {
          moment: 'An Orc hero is welcomed into the Horde’s proving ground.',
          setup: 'Eitrigg directs the new recruit toward Gornek and the first trial.',
          playerAction: 'The hero reports to Gornek in the Valley of Trials.',
          outcome: 'Training begins in earnest.',
          emotionalWeight: 'A harsh welcome: belonging must be proven.',
          chronicleEntry: 'Reported from Eitrigg to Gornek in the Valley of Trials, beginning a new life in the Horde.',
          tags: ['orc', 'horde', 'valley-of-trials', 'eitrigg', 'gornek'],
        },
        events: [
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Received Eitrigg’s opening direction.', npcName: 'Eitrigg', playerLevel: 1 },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Reported to Gornek.', npcName: 'Gornek' },
        ],
      },
      {
        stepId: 'valley-4641',
        questId: 4641,
        questName: 'Your Place in the World',
        wowheadUrl: 'https://classic.wowhead.com/quest=4641/your-place-in-the-world',
        zone: 'Valley of Trials',
        npcName: 'Kaltunk',
        npcId: 10176,
        storyCard: {
          moment: 'A Troll hero is sent to find their place among the Horde.',
          setup: 'Kaltunk points the new hero to Gornek, where the shared trials begin.',
          playerAction: 'The hero reports to Gornek in the Valley of Trials.',
          outcome: 'The Troll path joins the broader Horde proving ground.',
          emotionalWeight: 'An identity-forming first step into a hard world.',
          chronicleEntry: 'Followed Kaltunk’s direction to Gornek, seeking a place in the Horde’s Valley of Trials.',
          tags: ['troll', 'horde', 'valley-of-trials', 'kaltunk', 'gornek'],
        },
        events: [
          { kind: 'gossip_show', wowEvent: 'GOSSIP_SHOW', summary: 'Received Kaltunk’s opening direction.', npcName: 'Kaltunk', playerLevel: 1 },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Reported to Gornek.', npcName: 'Gornek' },
        ],
      },
      {
        stepId: 'valley-788',
        questId: 788,
        questName: 'Cutting Teeth',
        wowheadUrl: 'https://classic.wowhead.com/quest=788/cutting-teeth',
        zone: 'Valley of Trials',
        npcName: 'Gornek',
        npcId: 3143,
        storyCard: {
          moment: 'The hero proves basic survival by culling boars.',
          setup: 'Gornek demands action before trust.',
          playerAction: 'The hero kills Mottled Boars north of the Den.',
          outcome: 'The first trial is passed.',
          emotionalWeight: 'Simple, brutal initiation.',
          chronicleEntry: 'Passed Gornek’s first trial by cutting through Mottled Boars in the Valley of Trials.',
          tags: ['mottled-boar', 'gornek', 'survival', 'horde-training'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Gornek’s boar-hunting trial.', npcName: 'Gornek', playerLevel: 2 },
          { kind: 'quest_objective_progress', wowEvent: 'QUEST_PROGRESS', summary: 'Completed the Mottled Boar kill objective.', unitName: 'Mottled Boar' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Reported the completed boar trial to Gornek.', npcName: 'Gornek' },
        ],
      },
      {
        stepId: 'valley-789',
        questId: 789,
        questName: 'Sting of the Scorpid',
        wowheadUrl: 'https://classic.wowhead.com/quest=789/sting-of-the-scorpid',
        zone: 'Valley of Trials',
        npcName: 'Gornek',
        storyCard: {
          moment: 'The trial shifts from boars to venomous scorpids.',
          setup: 'Gornek needs scorpid tails for antidote work and further proof of competence.',
          playerAction: 'The hero kills scorpids and gathers their tails.',
          outcome: 'The Valley’s threats become familiar through blood and venom.',
          emotionalWeight: 'A harsher lesson: survival means understanding the land’s poisons.',
          chronicleEntry: 'Gathered scorpid tails for Gornek, learning the Valley of Trials through venom and dust.',
          tags: ['scorpid', 'venom', 'gornek', 'durotar'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Gornek’s scorpid task.', npcName: 'Gornek', playerLevel: 3 },
          { kind: 'quest_objective_progress', wowEvent: 'QUEST_PROGRESS', summary: 'Collected scorpid tails.', itemName: 'Scorpid Worker Tail' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned the scorpid tails to Gornek.', npcName: 'Gornek' },
        ],
      },
      {
        stepId: 'valley-790',
        questId: 790,
        questName: 'Sarkoth',
        wowheadUrl: 'https://classic.wowhead.com/quest=790/sarkoth',
        zone: 'Valley of Trials',
        npcName: "Hana'zua",
        npcId: 3287,
        storyCard: {
          moment: 'A wounded hunter asks the hero to kill Sarkoth.',
          setup: 'Hana’zua has been gored by a named scorpid and cannot finish the hunt.',
          playerAction: 'The hero climbs to Sarkoth’s plateau and slays the beast.',
          outcome: 'Hana’zua is avenged and the hero proves courage against a named threat.',
          emotionalWeight: 'A personal rescue wrapped in a starter-zone boss hunt.',
          chronicleEntry: 'Answered Hana’zua’s plea and slew Sarkoth, the scorpid that left him wounded on the Valley’s plateau.',
          tags: ['sarkoth', 'hanazua', 'named-kill', 'rescue', 'valley-of-trials'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted Hana’zua’s plea to kill Sarkoth.', npcName: "Hana'zua", playerLevel: 4 },
          { kind: 'unit_kill', wowEvent: 'COMBAT_LOG_EVENT_UNFILTERED', summary: 'Killed Sarkoth on the plateau.', unitName: 'Sarkoth' },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Returned to Hana’zua after killing Sarkoth.', npcName: "Hana'zua" },
        ],
      },
      {
        stepId: 'valley-804',
        questId: 804,
        questName: 'Sarkoth',
        wowheadUrl: 'https://classic.wowhead.com/quest=804/sarkoth',
        zone: 'Valley of Trials',
        npcName: "Hana'zua",
        storyCard: {
          moment: 'The hero reports Hana’zua’s condition back to Gornek.',
          setup: 'Sarkoth is dead, but Hana’zua still needs help.',
          playerAction: 'The hero returns to Gornek with word of the wounded hunter.',
          outcome: 'The Valley’s first real crisis closes with duty, not just victory.',
          emotionalWeight: 'Compassion after combat.',
          chronicleEntry: 'Reported Hana’zua’s condition to Gornek after killing Sarkoth, proving the trial was about duty as much as strength.',
          tags: ['sarkoth', 'gornek', 'hanazua', 'duty', 'horde'],
        },
        events: [
          { kind: 'quest_accepted', wowEvent: 'QUEST_ACCEPTED', summary: 'Accepted the report back to Gornek.', npcName: "Hana'zua" },
          { kind: 'quest_turned_in', wowEvent: 'QUEST_TURNED_IN', summary: 'Reported Hana’zua’s condition to Gornek.', npcName: 'Gornek', playerLevel: 5 },
        ],
      },
    ],
  },
];
